<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

|Term|Brief Description|
|----|-----------------|
|Subsetting|Extracting specific subsets or portions from a larger set. Used to access specific elements or sections of data structures eg arrays, lists of data frames. #my_list[1:4]|
|Indexing|accessing individual elements of a data structure using their position or index. zero-based, hence starts with index 0. #my_list[0] position 1, index 0|
|Slicing|extract a portion of a data structure based on specified start, stop and step indices eg list, array or string #my_list[2:6:2]|
|Masking|using a booleen mask to select or filter elements based on certain conditions. Each element is either 'True' or 'False'|  |

Exercise 2



In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [4]:
np_array_2d[::,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [5]:
x=np_array_2d[::,0]
y=x.astype(int)
print(y)

# astype(int) to convert elements of an array to the integer data type

[ 1  3  2  4  5  7  6  8 10  9]


In [6]:
y%2
#use % to get the remainder for division by 2, remainder 1 means that the element is odd

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [7]:
my_mask=y%2==1
my_mask
#check if the remainder is zero or not
#1 is the location of the odd numbers

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [8]:
np_array_2d[my_mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [9]:
np_array_2d[my_mask,1] #use the mask and extract the corresponding second element

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')