<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [ ]:
import numpy as np

# Subsetting: Indexing and Slicing

## Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"] 

In [2]:
py_list[0]

'a1'

In [3]:
py_list[-1]

'j10'

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"] 

In [5]:
py_list[0:3]   # "a1", "b2", "c3", "d4"?

['a1', 'b2', 'c3']

In [6]:
py_list[1:3]  #index 1 to 2

['b2', 'c3']

In [7]:
py_list[1:6] #index 1 to 5, 6-1=5 elements

['b2', 'c3', 'd4', 'e5', 'f6']

In [8]:
py_list[1:6:2] #index 1 to 5, in steps of 2

['b2', 'd4', 'f6']

In [9]:
py_list[5:] #index 5 to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [10]:
py_list[:5] #index 0 to index 4

['a1', 'b2', 'c3', 'd4', 'e5']

In [11]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

In [13]:
py_list[5:2:-1] #index 3 to 5 (in reverse)

['f6', 'e5', 'd4']

In [12]:
py_list[::-1] #reverses the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [14]:
py_list[::-2] #reverse the list in steps of 2

['j10', 'h8', 'f6', 'd4', 'b2']

## Arrays only | Subsetting by masking

In [17]:
import numpy as np

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask #subsetting by masking only works with numpy array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
np_array[my_mask] #show me only those that are true

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

**Example 1**

In [22]:
np_array[~(np_array > 3)]    # '~' means 'NOT'

array([1, 2, 3])

**Example 2**

In [23]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

**Example 3**

In [24]:
np_array[(np_array < 3) | (np_array > 8)]  # '|' means 'OR' - OR will show something if either mask is true

array([ 1,  2,  9, 10])

## Lists & Arrays in 2D | Indexing & Slicing

In [48]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

**Example 1**

In [28]:
py_list_2d[3]

[4, 'D']

In [29]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

**Example 2**

In [31]:
py_list_2d[3][0] #what is the first element in index 3  

4

In [30]:
np_array_2d[3,0]   

'4'

In [49]:
np_array_2d[::,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

**Example 3**

In [33]:
py_list_2d[:3] #first 3 elements, from index 0 to 2

[[1, 'A'], [2, 'B'], [3, 'C']]

In [32]:
np_array_2d[:3] 

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

**Example 4**

In [35]:
py_list_2d[:3][0] #first element of the list from py_list_2d[:3]

[1, 'A']

In [36]:
np_array_2d[:3,0] #first element in each of the three elements

array(['1', '2', '3'], dtype='<U11')

**Example 5**

In [35]:
py_list_2d[3:6][0]    #first element in index 4

[4, 'D']

In [38]:
np_array_2d[3:6, 0] #first elements in index 3,4,5

array(['4', '5', '6'], dtype='<U11')

In [34]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## Growing lists

In [36]:
x= [1, 2]*5 
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

**Example 1**

In [37]:
#growing a list by appending one element at a time
#append: adding or attaching something to the end of an existing object
x=[1]
x= x + [2] #appends the number 2 to the list 
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [41]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [42]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [43]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [45]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [38]:
x=[1, 2, 3]
x.append([4, 5, 6]) #adds the entire list [4,5,6] as a single element to the end of the list
x

[1, 2, 3, [4, 5, 6]]

In [39]:
[1,4,5,] + x

[1, 4, 5, 1, 2, 3, [4, 5, 6]]

## Some loose ends

## Tuples

In [43]:
a=[1,2,3,4,5]

In [44]:
a[0]=-161541449 #can assign value because this is a list

In [45]:
a

[-161541449, 2, 3, 4, 5]

In [46]:
a_tuple=(1,2,3,4,5)

In [ ]:
a_tuple[0] = 6198161 #cannot assign the value ot index 0 because this is a tuple

In [40]:
a=(1, 2, 3)     # Define tuple

In [41]:
print(a[0])    # Access data

1


In [ ]:
# The following will NOT work, we cannot change the data
a[0]=-1
a[0]+= [10] #trying to modify the element at index 0 of the list 'a' by adding another list '[10]' to it. 
# however a[0] is not a list, so it cannot be modified

## Be VERY careful when copying

In [67]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
#y and z now refer to the same list as 'x'
#any changes made to the list through one variable will be reflected in others eg y.append(4)

In [68]:
print(f'{id(x)=}, {id(y)=}, {id(z)=}')

id(x)=2643735960320, id(y)=2643735960320, id(z)=2643735960320


In [69]:
x=[1, 2, 3]
y=x.copy()
z=x.copy() #creating two separate copies of the list 'x' using the copy() method
print(f'{id(x)=}, {id(y)=}, {id(z)=}')

#the id() function in python returns the identity of an object, which is a unique identifier for that particular object
#the values for x, y, z are different - they are distinct objects in memory --> modification to one list won't affect the others

id(x)=2643755387712, id(y)=2643755325696, id(z)=2643755352896
