<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [21]:
import numpy as np

# Lists, Arrays & Dictionaries

## Let’s compare

**Python Lists**

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Arrays**

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#need two lists/array for the same data compared to the dictionary

**Dictionary**

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## Accessing data from a list (or array)

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Example 1**

In [3]:
py_real_names[0]

'Natasha Romanoff'

**Example 2**

In [4]:
py_super_names[0]

'Black Widow'

In [10]:
i=2
print(py_real_names[i],' is ',py_super_names[i])

Stephen Strange  is  Doctor Strange


**Example 3**

In [11]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [12]:
py_super_names[-1] #reverse indexing

'Doctor Strange'

## Accessing data from a dictionary

In [2]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [18]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [3]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [12]:
superhero_info.values() 

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## Higher dimensional lists

In [13]:
py_superhero_info = [
    ['Natasha Romanoff', 'Black Widow'],
    ['Tony Stark', 'Iron Man'],
    ['Stephen Strange', 'Doctor Strange']
]

#2d list or array

# Lists vs. Arrays

In [22]:
py_list_2d = [
    [1, "A"],
    [2, "B"],
    [3, "C"],
    [4, "D"],
    [5, "E"],
    [6, "F"],
    [7, "G"],
    [8, "H"],
    [9, "I"],
    [10, "J"]
    ]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [20]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [27]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

## Size

**Lists**

In [28]:
len(py_list_2d) #length of the list

10

**Arrays**

In [29]:
len(np_array_2d)

10

In [36]:
np_array_2d.shape #find the dimension, row x column

(10, 2)

## Arrays are fussy about type

In [37]:
py_list = [1, 1.5, 'A'] #list has no dimension
np_array = np.array(py_list) #array has no dimension 

**Lists**

In [38]:
py_list

[1, 1.5, 'A']

**Arrays**

In [39]:
np_array #arrays insist on having only a single data type, numbers are converted to english #lists can have more data types

array(['1', '1.5', 'A'], dtype='<U32')

## Adding a number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [28]:
py_list

[1, 2, 3, 4, 5]

In [29]:
np_array

array([1, 2, 3, 4, 5])

**Lists**

In [ ]:
py_list + 10        # Won't work! 

**Arrays**

In [31]:
np_array + 100 #adding 100 to every number in the array 

array([101, 102, 103, 104, 105])

## Adding another list

In [45]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

**Lists**

In [46]:
py_list_1 + py_list_2 #combining two lists side by side 

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [47]:
np_array_1 + np_array_2 #adding the numbers within 

array([11, 22, 33, 44, 55])

## Multiplying by a Number

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [49]:
py_list*2 #show the list twice

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays**

In [50]:
np_array*2 #multiplying 2 to each number 

array([ 2,  4,  6,  8, 10])

## Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

**Lists**

In [ ]:
py_list**2                      # Won't work!  

**Arrays**

In [51]:
np_array**2

array([ 1,  4,  9, 16, 25])

## Asking questions

In [55]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [57]:
py_list == 3     # Works, but what IS the question?

False

In [ ]:
py_list > 3      # Won't work!

**Arrays**

In [60]:
np_array

array([1, 2, 3, 4, 5])

In [58]:
np_array == 3  

array([False, False,  True, False, False])

In [62]:
np_array > 3

array([False, False, False,  True,  True])

In [61]:
sum(np_array > 3)  #number of numbers that are more than 2 in the array 

2

## Mathematics

In [67]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Example 1**

**Lists**

In [68]:
sum(py_list)     # sum() is a base Python function

15

In [ ]:
py_list.sum()   # Won't work! basic python does not have the sum() method, but works for numpy 

**Arrays**

In [70]:
sum(np_array)

15

In [69]:
np_array.sum()

15

**Example 2**

**Lists**

In [71]:
max(py_list)     # max() is a base Python function

5

**Arrays**

In [72]:
np_array.max()

5

**Example 3**

**Lists**

In [73]:
min(py_list)

1

**Arrays**

In [74]:
np_array.min()

1

**Example 4**

In [76]:
np_array.mean()

3.0

In [77]:
np_array.std()

1.4142135623730951

In [ ]:
#an operation on a list works on a whole list. operation in array works on the individual elements of the array